/// Flutter icons Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Icons {
  Icons._();

  static const _kFontFam = 'Icons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_ind = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_5 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_file = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cached = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble_outline = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_point = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_download = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_align_justify = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reorder = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_circle_outline = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storage = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out_map = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
